from enum import Enum, auto

class TokenEnum(Enum):
  ATE = auto(),
  ATR = auto(),
  E = auto(),
  ENTAO = auto(),
  ESCREVA = auto(),
  FIMPARA = auto(),
  FIMSE = auto(),
  ID = auto(),
  LEIA = auto(),
  LOGDIFF = auto(),
  LOGIGUAL = auto(),
  LOGMAIOR = auto(),
  LOGMAIORIGUAL = auto(),
  LOGMENOR = auto(),
  LOGMENORIGUAL = auto(),
  NAO = auto(),
  NUMINT = auto(),
  OPDIVI = auto(),
  OPMAIS = auto(),
  OPMENOS = auto(),
  OPMULTI = auto(),
  OU = auto(),
  PARA = auto(),
  PARAB = auto(),
  PARFE = auto(),
  PASSO = auto(),
  SE = auto(),
  SENAO = auto(),
  STRING = auto(),
  TIPO = auto(),

  # Additional Tokens (not in documentation)
  ALGORITMO = auto(),
  VAR = auto(),
  COMMA = auto(),
  COLON = auto(),
  INICIO = auto(),
  FIMALGORITMO = auto(),
